stages:
  prepare:
    cmd: python notebooks/lab3/create_features_w_params.py
    deps:
      - data/adult.data
      - data/adult.test
      - notebooks/lab3/create_features_w_params.py
    outs:
      - data/pipeline.pkl
      - data/processed_train_data.csv
      - data/processed_test_data.csv
    params:
      - features.chi2percentile
      - features.train_path
      - features.test_path

  iris_prepare:
    cmd: python src/preprocessing.py
    deps:
      - data/iris.csv
      - src/preprocessing.py
    outs:
      - data/iris_pipeline.pkl
      - data/iris_processed_train_data.csv
      - data/iris_processed_test_data.csv
