apiVersion: v1
kind: Service
metadata:
  name: reddit-service
spec:
  # type: NodePort
  selector:
    app: reddit
  ports:
    # - port: 80
    #   targetPort: 8000
    #   nodePort: 30007
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: LoadBalancer
